[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300  # Increased timeout
restartPolicy = "always"

[deploy.env]
PYTHON_VERSION = "3.11" 